#ifndef HALDEFINITIONS_H
#define HALDEFINITIONS_H

//////// PROTOCOLS
#define PROT_NEXA_SELFLEARNING
#define PROT_OREGON_SELFLEARNING

/////// HARDWARE
#define HW_BH1750
#define HW_DHT11
#define HW_PHOTOCELL


#endif // HALDEFINITIONS_H